<?php
/**
 * lemocms
 * ============================================================================
 * 版权所有 2018-2027 lemocms，并保留所有权利。
 * 网站地址: https://www.lemocms.com
 * ----------------------------------------------------------------------------
 * 采用最新Thinkphp6实现
 * ============================================================================
 * Author: yuege
 * Date: 2019/9/21
 */


namespace app\common\controller;

use app\BaseController;
use app\common\model\Config;
use think\facade\Request;
use think\facade\Cookie;
use think\View;

class Frontend extends BaseController
{

    public  $uid=1;
    public $pageSize=15;
    public function initialize()
    {
       $config=getConfig();


        \think\facade\View::assign('config', $config);
        \think\facade\View::assign('nickname',session('user.nickname') );
        $this->pageSize= Request::post('limit') ? Request::post('limit') : 15;

        parent::initialize(); // TODO: Change the autogenerated stub
    }


}