<?php
/**
 * lemocms
 * ============================================================================
 * 版权所有 2018-2027 lemocms，并保留所有权利。
 * 网站地址: https://www.lemocms.com
 * ----------------------------------------------------------------------------
 * 采用最新Thinkphp6实现
 * ============================================================================
 * Author: yuege
 * Date: 2019/9/21
 */


namespace app\common\controller;

use app\BaseController;
use app\common\model\Config;
use think\facade\Request;
use think\facade\Cookie;
use think\View;

class Privates extends Frontend
{

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        //判断管理员是否登录
        if (!session('user.id') && !session('user')) {
            $this->redirect(url('/index/login/index'));
        }

        $this->uid=session('user.id');
        $this->pageSize= Request::post('limit') ? Request::post('limit') : 15;

    }


}