<?php
/**
 * lemocms
 * ============================================================================
 * 版权所有 2018-2027 lemocms，并保留所有权利。
 * 网站地址: https://www.lemocms.com
 * ----------------------------------------------------------------------------
 * 采用最新Thinkphp6实现
 * ============================================================================
 * Author: yuege
 * Date: 2019/8/2
 */
namespace app\mer\controller\order;

use app\common\controller\Backend;
use app\common\model\GoodsClazz;
use lemo\helper\TreeHelper;
use think\facade\Db;
use think\facade\Request;
use think\facade\View;
use app\common\model\PayChannel as PayChannelModel;
use think\Validate;

class Channel extends Backend
{


    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }
    /**
     * 商品分类
     * @return array|string
     * @throws \think\db\exception\DbException
     */
    public function index()
    {
        if (Request::isPost()) {
            $keys = Request::post('keys', '', 'trim');
            $page = Request::post('page') ? Request::post('page') : 1;
            $list = null;
            if (!$list) {
                $list = Db::name('pay_channel')
                    ->where('title', 'like', '%' . $keys . '%')
                    ->paginate(['list_rows' => $this->pageSize, 'page' => $page])
                    ->toArray();
                foreach ($list['data'] as $k => $v) {
                    $list['data'][$k]['lay_is_open'] = false;
                }

            }


            return $result = ['code' => 0,
                'msg' => lang('get info success'), 'data' => $list['data'], 'count' => $list['total']];

        }
        return View::fetch();
    }


    public function add()
    {

        if (Request::isPost()) {

            $data = Request::post();
            $res = \app\common\model\PayChannel::create($data);
            if ($res) {
                $this->success(lang('add success'));
            } else {
                $this->error(lang('add fail'));

            }
        } else {
            $goodsClass = \app\common\model\PayChannel::where('status', 1)->select()->toArray();
            $goodsClass = TreeHelper::cateTree($goodsClass);
           $payList=get_service_list();


          $javaList= get_java_service_list();


            $params['name'] = 'container';
            $params['content'] = '';
            $view = [
                'info' => '',
                'payList'=>$payList,
                'javaList'=>$javaList,
                'goodsClass' => $goodsClass,
                'title' => lang('add'),
                'ueditor' => build_ueditor($params),
            ];
            View::assign($view);
            return View::fetch();
        }
    }


    public function edit()
    {
        if (Request::isPost()) {
            $data = Request::post();
            if (!$data['id']) {
                $this->error(lang('invalid data'));
            }

            $res = \app\common\model\PayChannel::update($data);
            if ($res) {
                $this->success(lang('edit success'));
            } else {
                $this->error(lang('edit fail'));

            }
        } else {
            $id = Request::get('id');
            $goodsClass = \app\common\model\PayChannel::where('status', 1)->select()->toArray();
            $goodsClass = TreeHelper::cateTree($goodsClass);
            $params['name'] = 'container';
            $params['content'] = '';
            $info = \app\common\model\PayChannel::find($id);
            $payList=get_service_list();
            $javaList= get_java_service_list();

            $view = [
                'info' => $info,
                'goodsClass' => $goodsClass,
                'payList'=>$payList,
                'javaList'=>$javaList,
                'title' => lang('add'),
                'ueditor' => build_ueditor($params),
            ];
            View::assign($view);
            return View::fetch('add');
        }


    }
    public function state()
    {
        $id = Request::post('id');
        if ($id) {
            $where['id'] = $id;

            $link = PayChannelModel::find($id);
            $where['status'] = $link['status'] ? 0 : 1;
            PayChannelModel::update($where);

            $this->success(lang('edit success'));

        } else {
            $this->error(lang('edit fail'));

        }


    }
}