<?php
/**
 * lemocms
 * ============================================================================
 * 版权所有 2018-2027 lemocms，并保留所有权利。
 * 网站地址: https://www.lemocms.com
 * ----------------------------------------------------------------------------
 * 采用最新Thinkphp6实现
 * ============================================================================
 * Author: yuege
 * Date: 2019/9/4
 */
namespace app\admin\controller\order;
use app\common\controller\Backend;
use think\facade\Db;
use think\facade\Request;
use think\facade\View;
use app\common\model\WxAccount;
use lemo\service\WechatApp;
use lemo\helper\DataHelper;

use app\common\model\WxFans;
use app\common\model\WxMaterial;
use app\common\model\WxMaterialInfo;
use app\common\model\WxMsgHistory;
use app\common\model\WxReply;
use app\common\model\WxTag;

use EasyWeChat\Kernel\Messages\Text;
use EasyWeChat\Kernel\Messages\Article;
use EasyWeChat\Kernel\Messages\Image;
use EasyWeChat\Kernel\Messages\Video;
use EasyWeChat\Kernel\Messages\Voice;
use EasyWeChat\Kernel\Messages\News;
use EasyWeChat\Kernel\Messages\NewsItem;

class Pay extends Backend {

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated

    }



    /**
     ************************支付管理****************************
     */
    public function index(){
        var_dump(11);
        if (Request::isPost()) {
            $list = Db::name('order_pay')->alias('a')
                ->leftJoin('wx_type t','t.type_id=a.type')
                ->field('a.*,t.name as type_name')->cache(3600)
                ->select()->toArray();

            return $result = ['code' => 0, 'msg' =>lang('get info success'), 'data' => $list,];
        }
        return view();

    }

    public function add(){
        if (Request::isPost()) {
            $data = Request::post();
            try{
                $this->validate($data, 'WxAccount');
            }catch (\Exception $e){
                $this->error($e->getMeussage());
            }
            $data['weixin'] = $data['wxname'];
            $res = WxAccount::create($data);
            if ($res) {
                $this->success(lang('add success'),url('index'));
            } else {
                $this->error(lang('add fail'));
            }
        }
        $view = [
            'info' => '',
            'title' => lang('add'),
        ];
        View::assign($view);
        return view();
    }

    public function edit(){
        if (Request::isPost()) {
            $data = Request::post();
            try {
                $this->validate($data, 'WxAccount');
            } catch (\Exception $e) {
                $this->error($e->getMessage());
            }
            $res = WxAccount::update($data);
            if ($res) {
                $this->success(lang('edit success'), url('index'));
            } else {
                $this->error(lang('edit fail'));
            }
        }
        $info = WxAccount::cache(3600)->find(Request::get('id'));
        $view = [
            'info' => $info,
            'title' => '修改',
        ];
        View::assign($view);
        return view('add');

    }
    public function state(){

        $id = Request::post('id');
        if($id){
            $info = WxAccount::cache(3600)->find($id);
            $info->status = $info->status==1?0:1;
            if($info->status==1){
                $list = WxAccount::where('status',1)->where('id','<>',$info->id)->select();
                if($list){
                    foreach ($list as $k=>$v){
                        $v->status=0;
                        $v->save();
                    }
                }
            }
            $info->save();
            $this->success(lang('edit success'));
        }else{
            $this->error('非法数据');
        }
    }
    public function delete(){
        $id = Request::post('id');
        if($id){
            WxAccount::destroy($id);
            $this->success(lang('delete success'));

        }else{
            $this->error('非法数据');
        }

    }


}