<?php


namespace app\finance\controller\order;


use app\common\controller\Backend;
use think\facade\Db;
use think\facade\Request;
use think\facade\View;

class Missorder extends Backend
{


    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * 商品分类
     * @return array|string
     * @throws \think\db\exception\DbException
     */
    public function index()
    {
        if (Request::isPost()) {
            $keys = Request::post('keys', '', 'trim');
            $page = Request::post('page') ? Request::post('page') : 1;
            $list = null;
            if (!$list) {
                $list = Db::name('pay_missorder')
//                    ->where('title', 'like', '%' . $keys . '%')
                        ->order(['id desc'])
                    ->paginate(['list_rows' => $this->pageSize, 'page' => $page])

                    ->toArray();


            }


            return $result = ['code' => 0,
                'msg' => lang('get info success'), 'data' => $list['data'], 'count' => $list['total']];

        }
        return View::fetch();
    }
}